steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/braided-facet-481008-j9/jamjam-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/braided-facet-481008-j9/jamjam-backend:latest'
      - '-f'
      - 'Dockerfile.backend'
      - '.'
images:
  - 'gcr.io/braided-facet-481008-j9/jamjam-backend:$SHORT_SHA'
  - 'gcr.io/braided-facet-481008-j9/jamjam-backend:latest'
timeout: 600s
