_wandb:
    value:
        cli_version: 0.25.1
        e:
            ljhe1k0r49q462sklska4i03e6wfyqyn:
                codePath: model/upload_to_wandb.py
                codePathLocal: model/upload_to_wandb.py
                email: sgim49697@gmail.com
                executable: /home/user/projects/JamJamBeat/model/.venv/bin/python3
                git:
                    commit: dd9f3c7db0826009297c7bcb0d15bfd7ee30c480
                    remote: https://github.com/saehoon861/JamJamBeat
                host: sgkim
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/user/projects/JamJamBeat/model/upload_to_wandb.py
                python: CPython 3.12.12
                root: /home/user/projects/JamJamBeat
                startedAt: "2026-03-12T03:09:19.851028Z"
                writerId: ljhe1k0r49q462sklska4i03e6wfyqyn
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.12.12
            "5": 0.25.1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 32
device:
    value: cpu
epochs:
    value: 20
epochs_ran:
    value: 7
focal_gamma:
    value: 2
lr:
    value: 0.001
mode:
    value: sequence
model_id:
    value: cnn1d_tcn
optimizer:
    value: AdamW
patience:
    value: 6
test_samples:
    value: 12310
train_samples:
    value: 24330
val_samples:
    value: 8843
weight_decay:
    value: 0.0001
