_wandb:
    value:
        cli_version: 0.25.1
        e:
            8ligvzqwuqvt4j7bmfmr4g7obks2v86r:
                codePath: model/upload_to_wandb.py
                codePathLocal: model/upload_to_wandb.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "34419630080"
                email: sgim49697@gmail.com
                executable: /home/user/projects/JamJamBeat/model/.venv/bin/python3
                git:
                    commit: dd9f3c7db0826009297c7bcb0d15bfd7ee30c480
                    remote: https://github.com/saehoon861/JamJamBeat
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-abde4396-068b-c4cf-7ca6-ad4d47637cdf
                host: sgkim
                memory:
                    total: "8325890048"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/user/projects/JamJamBeat/model/upload_to_wandb.py
                python: CPython 3.12.12
                root: /home/user/projects/JamJamBeat
                startedAt: "2026-03-12T03:10:01.752089Z"
                writerId: 8ligvzqwuqvt4j7bmfmr4g7obks2v86r
        m: []
        python_version: 3.12.12
        t:
            "3":
                - 2
                - 13
                - 15
            "4": 3.12.12
            "5": 0.25.1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
