_wandb:
    value:
        cli_version: 0.25.0
        e:
            y14q5xl85p9h9xlk2j1azfl6vmgm0kll:
                args:
                    - --csv-path
                    - /home/kimsaehoon/workspace/JamJamBeat/data/total_data_0309.csv
                    - --label-col
                    - gesture
                    - --input-size
                    - "63"
                    - --num-classes
                    - "7"
                    - --hidden-dims
                    - 128,64
                    - --batch-size
                    - "256"
                    - --num-epochs
                    - "50"
                    - --learning-rate
                    - "0.0005"
                    - --dropout
                    - "0.005"
                    - --weight-decay
                    - "0.0001"
                    - --use-batchnorm
                    - "True"
                    - --test-split-seed
                    - "42"
                    - --train-val-split-seed
                    - "7"
                    - --train-seed
                    - "42"
                    - --scheduler-name
                    - ReduceLROnPlateau
                codePath: src/training/train.py
                codePathLocal: src/training/train.py
                cpu_count: 14
                cpu_count_logical: 28
                disk:
                    /:
                        total: "1081101176832"
                        used: "16474169344"
                email: qazxcv39372046@gmail.com
                executable: /home/kimsaehoon/workspace/JamJamBeat/.venv/bin/python3
                git:
                    commit: 0b9e5458e410fc0426cbd6cfaffea74e9c5480c8
                    remote: git@github.com:saehoon861/JamJamBeat.git
                host: DESKTOP-EM38RML
                memory:
                    total: "16602247168"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/kimsaehoon/workspace/JamJamBeat/src/training/train.py
                python: CPython 3.11.14
                root: /home/kimsaehoon/workspace/JamJamBeat
                startedAt: "2026-03-09T14:35:27.743719Z"
                writerId: y14q5xl85p9h9xlk2j1azfl6vmgm0kll
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 16
            "4": 3.11.14
            "5": 0.25.0
            "10":
                - 20
            "12": 0.25.0
            "13": linux-x86_64
balance_train:
    value: true
batch_size:
    value: 256
csv_path:
    value: /home/kimsaehoon/workspace/JamJamBeat/data/total_data_0309.csv
dropout:
    value: 0.005
early_stopping_min_delta:
    value: 0.0001
early_stopping_patience:
    value: 5
feature_columns:
    value:
        - x0
        - y0
        - z0
        - x1
        - y1
        - z1
        - x2
        - y2
        - z2
        - x3
        - y3
        - z3
        - x4
        - y4
        - z4
        - x5
        - y5
        - z5
        - x6
        - y6
        - z6
        - x7
        - y7
        - z7
        - x8
        - y8
        - z8
        - x9
        - y9
        - z9
        - x10
        - y10
        - z10
        - x11
        - y11
        - z11
        - x12
        - y12
        - z12
        - x13
        - y13
        - z13
        - x14
        - y14
        - z14
        - x15
        - y15
        - z15
        - x16
        - y16
        - z16
        - x17
        - y17
        - z17
        - x18
        - y18
        - z18
        - x19
        - y19
        - z19
        - x20
        - y20
        - z20
gamma:
    value: 0.5
hidden_dims:
    value:
        - 128
        - 64
input_size:
    value: 63
label_col:
    value: gesture
learning_rate:
    value: 0.0005
majority_class:
    value: 0
majority_ratio:
    value: 1.5
num_classes:
    value: 7
num_epochs:
    value: 50
optimizer_name:
    value: adam
save_name:
    value: best_model.pth
scheduler_name:
    value: ReduceLROnPlateau
step_size:
    value: 5
test_split_ratio:
    value: 0.1
test_split_seed:
    value: 42
train_seed:
    value: 42
train_val_split_seed:
    value: 7
use_batchnorm:
    value: true
validation_split_ratio:
    value: 0.2
weight_decay:
    value: 0.0001
